# Generated by Django 5.2.6 on 2025-09-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtemplate',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submissionfile',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='schema',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='submissionfile',
            name='field_key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='submissionfile',
            name='original_filename',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.DeleteModel(
            name='Field',
        ),
    ]
